// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEOhp1WzsVDfYBhNfFAYQxjX4Pcijqe8E',
    appId: '1:811980426793:web:03c1d07c6726b489d79638',
    messagingSenderId: '811980426793',
    projectId: 'foodcarts-3b27a',
    authDomain: 'foodcarts-3b27a.firebaseapp.com',
    storageBucket: 'foodcarts-3b27a.firebasestorage.app',
    measurementId: 'G-FVH4227B0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8OcQE1vOshFrLHUaM3Xcu9UuhZEFfbU',
    appId: '1:811980426793:android:85c58e8fb2665a73d79638',
    messagingSenderId: '811980426793',
    projectId: 'foodcarts-3b27a',
    storageBucket: 'foodcarts-3b27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTKW76gGB540s5McvlvLTKrXaH9FYE5_4',
    appId: '1:811980426793:ios:76c0bf7012aebfebd79638',
    messagingSenderId: '811980426793',
    projectId: 'foodcarts-3b27a',
    storageBucket: 'foodcarts-3b27a.firebasestorage.app',
    iosBundleId: 'com.example.dishCategoriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTKW76gGB540s5McvlvLTKrXaH9FYE5_4',
    appId: '1:811980426793:ios:76c0bf7012aebfebd79638',
    messagingSenderId: '811980426793',
    projectId: 'foodcarts-3b27a',
    storageBucket: 'foodcarts-3b27a.firebasestorage.app',
    iosBundleId: 'com.example.dishCategoriesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEOhp1WzsVDfYBhNfFAYQxjX4Pcijqe8E',
    appId: '1:811980426793:web:4761b773592c8206d79638',
    messagingSenderId: '811980426793',
    projectId: 'foodcarts-3b27a',
    authDomain: 'foodcarts-3b27a.firebaseapp.com',
    storageBucket: 'foodcarts-3b27a.firebasestorage.app',
    measurementId: 'G-PBV7381137',
  );
}
